//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HS.MACConnect.com.alarmaccount.www {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NMCLinkPortalSoap", Namespace="http://www.nmccentral.com/webservices/nmcmapi")]
    public partial class NMCLinkPortal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProcessDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessDataRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessDataElementRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessDataElementRequest2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NMCLinkPortal() {
            this.Url = global::HS.MACConnect.Properties.Settings.Default.HS_MACConnect_com_alarmaccount_www_NMCLinkPortal;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcessDataCompletedEventHandler ProcessDataCompleted;
        
        /// <remarks/>
        public event ProcessDataRequestCompletedEventHandler ProcessDataRequestCompleted;
        
        /// <remarks/>
        public event ProcessDataElementRequestCompletedEventHandler ProcessDataElementRequestCompleted;
        
        /// <remarks/>
        public event ProcessDataElementRequest2CompletedEventHandler ProcessDataElementRequest2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nmccentral.com/webservices/nmcmapi/ProcessData", RequestNamespace="http://www.nmccentral.com/webservices/nmcmapi", ResponseNamespace="http://www.nmccentral.com/webservices/nmcmapi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProcessData(string reqType, string secUser, string passWord, string csNo, string xmldata) {
            object[] results = this.Invoke("ProcessData", new object[] {
                        reqType,
                        secUser,
                        passWord,
                        csNo,
                        xmldata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessDataAsync(string reqType, string secUser, string passWord, string csNo, string xmldata) {
            this.ProcessDataAsync(reqType, secUser, passWord, csNo, xmldata, null);
        }
        
        /// <remarks/>
        public void ProcessDataAsync(string reqType, string secUser, string passWord, string csNo, string xmldata, object userState) {
            if ((this.ProcessDataOperationCompleted == null)) {
                this.ProcessDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessDataOperationCompleted);
            }
            this.InvokeAsync("ProcessData", new object[] {
                        reqType,
                        secUser,
                        passWord,
                        csNo,
                        xmldata}, this.ProcessDataOperationCompleted, userState);
        }
        
        private void OnProcessDataOperationCompleted(object arg) {
            if ((this.ProcessDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessDataCompleted(this, new ProcessDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nmccentral.com/webservices/nmcmapi/ProcessDataRequest", RequestNamespace="http://www.nmccentral.com/webservices/nmcmapi", ResponseNamespace="http://www.nmccentral.com/webservices/nmcmapi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ProcessDataRequest(InputParms inP) {
            object[] results = this.Invoke("ProcessDataRequest", new object[] {
                        inP});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessDataRequestAsync(InputParms inP) {
            this.ProcessDataRequestAsync(inP, null);
        }
        
        /// <remarks/>
        public void ProcessDataRequestAsync(InputParms inP, object userState) {
            if ((this.ProcessDataRequestOperationCompleted == null)) {
                this.ProcessDataRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessDataRequestOperationCompleted);
            }
            this.InvokeAsync("ProcessDataRequest", new object[] {
                        inP}, this.ProcessDataRequestOperationCompleted, userState);
        }
        
        private void OnProcessDataRequestOperationCompleted(object arg) {
            if ((this.ProcessDataRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessDataRequestCompleted(this, new ProcessDataRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nmccentral.com/webservices/nmcmapi/ProcessDataElementRequest", RequestNamespace="http://www.nmccentral.com/webservices/nmcmapi", ResponseNamespace="http://www.nmccentral.com/webservices/nmcmapi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ProcessDataElementRequest(InputParms inParms) {
            object[] results = this.Invoke("ProcessDataElementRequest", new object[] {
                        inParms});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessDataElementRequestAsync(InputParms inParms) {
            this.ProcessDataElementRequestAsync(inParms, null);
        }
        
        /// <remarks/>
        public void ProcessDataElementRequestAsync(InputParms inParms, object userState) {
            if ((this.ProcessDataElementRequestOperationCompleted == null)) {
                this.ProcessDataElementRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessDataElementRequestOperationCompleted);
            }
            this.InvokeAsync("ProcessDataElementRequest", new object[] {
                        inParms}, this.ProcessDataElementRequestOperationCompleted, userState);
        }
        
        private void OnProcessDataElementRequestOperationCompleted(object arg) {
            if ((this.ProcessDataElementRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessDataElementRequestCompleted(this, new ProcessDataElementRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.nmccentral.com/webservices/nmcmapi/ProcessDataElementRequest2", RequestNamespace="http://www.nmccentral.com/webservices/nmcmapi", ResponseNamespace="http://www.nmccentral.com/webservices/nmcmapi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ProcessDataElementRequest2(OnTestParms ontestParms) {
            object[] results = this.Invoke("ProcessDataElementRequest2", new object[] {
                        ontestParms});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessDataElementRequest2Async(OnTestParms ontestParms) {
            this.ProcessDataElementRequest2Async(ontestParms, null);
        }
        
        /// <remarks/>
        public void ProcessDataElementRequest2Async(OnTestParms ontestParms, object userState) {
            if ((this.ProcessDataElementRequest2OperationCompleted == null)) {
                this.ProcessDataElementRequest2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessDataElementRequest2OperationCompleted);
            }
            this.InvokeAsync("ProcessDataElementRequest2", new object[] {
                        ontestParms}, this.ProcessDataElementRequest2OperationCompleted, userState);
        }
        
        private void OnProcessDataElementRequest2OperationCompleted(object arg) {
            if ((this.ProcessDataElementRequest2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessDataElementRequest2Completed(this, new ProcessDataElementRequest2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nmccentral.com/webservices/nmcmapi")]
    public partial class InputParms {
        
        private System.Nullable<int> siteNoField;
        
        private System.Nullable<int> systemNoField;
        
        private System.Nullable<int> contactNoField;
        
        private string reqTypeField;
        
        private string secUserField;
        
        private string procNameField;
        
        private string csNoField;
        
        private string xmlDataField;
        
        private string appFlagField;
        
        private string passWordField;
        
        private string xmlStringField;
        
        private string pINField;
        
        private string codeWordField;
        
        private string sitePhoneField;
        
        private string panelCodeField;
        
        private System.Nullable<int> cust_noField;
        
        private string site_nameField;
        
        private string altIDField;
        
        private string email_addressField;
        
        private string contactPhoneField;
        
        private System.Nullable<int> empNoField;
        
        private string udf1Field;
        
        private string udf2Field;
        
        private string udf3Field;
        
        private string udf4Field;
        
        private System.Nullable<int> branchNoField;
        
        private System.Nullable<int> coNoField;
        
        private System.Nullable<int> installNoField;
        
        private System.Nullable<int> servcoNoField;
        
        private System.Nullable<int> corpAcctNoField;
        
        private string startDateField;
        
        private string endDateField;
        
        private System.Nullable<int> historyRowsField;
        
        private string openOnlyField;
        
        private string invoiceOnlyField;
        
        private string sortOrderField;
        
        private string useHistoryField;
        
        private string dbFlagField;
        
        private string startBillCodeField;
        
        private string endBillCodeField;
        
        private string hideReverseField;
        
        private string retAddrField;
        
        private System.Nullable<int> invFromField;
        
        private System.Nullable<int> invToField;
        
        private System.Nullable<int> spidField;
        
        private string emailFlagField;
        
        private System.Nullable<int> invFormNoField;
        
        private System.Nullable<int> invoiceNoField;
        
        private System.Nullable<int> ctactLinkNoField;
        
        private string processNameField;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> siteNo {
            get {
                return this.siteNoField;
            }
            set {
                this.siteNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> systemNo {
            get {
                return this.systemNoField;
            }
            set {
                this.systemNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> contactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
            }
        }
        
        /// <remarks/>
        public string reqType {
            get {
                return this.reqTypeField;
            }
            set {
                this.reqTypeField = value;
            }
        }
        
        /// <remarks/>
        public string secUser {
            get {
                return this.secUserField;
            }
            set {
                this.secUserField = value;
            }
        }
        
        /// <remarks/>
        public string procName {
            get {
                return this.procNameField;
            }
            set {
                this.procNameField = value;
            }
        }
        
        /// <remarks/>
        public string csNo {
            get {
                return this.csNoField;
            }
            set {
                this.csNoField = value;
            }
        }
        
        /// <remarks/>
        public string xmlData {
            get {
                return this.xmlDataField;
            }
            set {
                this.xmlDataField = value;
            }
        }
        
        /// <remarks/>
        public string appFlag {
            get {
                return this.appFlagField;
            }
            set {
                this.appFlagField = value;
            }
        }
        
        /// <remarks/>
        public string passWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        public string xmlString {
            get {
                return this.xmlStringField;
            }
            set {
                this.xmlStringField = value;
            }
        }
        
        /// <remarks/>
        public string PIN {
            get {
                return this.pINField;
            }
            set {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        public string codeWord {
            get {
                return this.codeWordField;
            }
            set {
                this.codeWordField = value;
            }
        }
        
        /// <remarks/>
        public string sitePhone {
            get {
                return this.sitePhoneField;
            }
            set {
                this.sitePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string panelCode {
            get {
                return this.panelCodeField;
            }
            set {
                this.panelCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> cust_no {
            get {
                return this.cust_noField;
            }
            set {
                this.cust_noField = value;
            }
        }
        
        /// <remarks/>
        public string site_name {
            get {
                return this.site_nameField;
            }
            set {
                this.site_nameField = value;
            }
        }
        
        /// <remarks/>
        public string altID {
            get {
                return this.altIDField;
            }
            set {
                this.altIDField = value;
            }
        }
        
        /// <remarks/>
        public string email_address {
            get {
                return this.email_addressField;
            }
            set {
                this.email_addressField = value;
            }
        }
        
        /// <remarks/>
        public string contactPhone {
            get {
                return this.contactPhoneField;
            }
            set {
                this.contactPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> empNo {
            get {
                return this.empNoField;
            }
            set {
                this.empNoField = value;
            }
        }
        
        /// <remarks/>
        public string udf1 {
            get {
                return this.udf1Field;
            }
            set {
                this.udf1Field = value;
            }
        }
        
        /// <remarks/>
        public string udf2 {
            get {
                return this.udf2Field;
            }
            set {
                this.udf2Field = value;
            }
        }
        
        /// <remarks/>
        public string udf3 {
            get {
                return this.udf3Field;
            }
            set {
                this.udf3Field = value;
            }
        }
        
        /// <remarks/>
        public string udf4 {
            get {
                return this.udf4Field;
            }
            set {
                this.udf4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> branchNo {
            get {
                return this.branchNoField;
            }
            set {
                this.branchNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> coNo {
            get {
                return this.coNoField;
            }
            set {
                this.coNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> installNo {
            get {
                return this.installNoField;
            }
            set {
                this.installNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> servcoNo {
            get {
                return this.servcoNoField;
            }
            set {
                this.servcoNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> corpAcctNo {
            get {
                return this.corpAcctNoField;
            }
            set {
                this.corpAcctNoField = value;
            }
        }
        
        /// <remarks/>
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> historyRows {
            get {
                return this.historyRowsField;
            }
            set {
                this.historyRowsField = value;
            }
        }
        
        /// <remarks/>
        public string openOnly {
            get {
                return this.openOnlyField;
            }
            set {
                this.openOnlyField = value;
            }
        }
        
        /// <remarks/>
        public string invoiceOnly {
            get {
                return this.invoiceOnlyField;
            }
            set {
                this.invoiceOnlyField = value;
            }
        }
        
        /// <remarks/>
        public string sortOrder {
            get {
                return this.sortOrderField;
            }
            set {
                this.sortOrderField = value;
            }
        }
        
        /// <remarks/>
        public string useHistory {
            get {
                return this.useHistoryField;
            }
            set {
                this.useHistoryField = value;
            }
        }
        
        /// <remarks/>
        public string dbFlag {
            get {
                return this.dbFlagField;
            }
            set {
                this.dbFlagField = value;
            }
        }
        
        /// <remarks/>
        public string startBillCode {
            get {
                return this.startBillCodeField;
            }
            set {
                this.startBillCodeField = value;
            }
        }
        
        /// <remarks/>
        public string endBillCode {
            get {
                return this.endBillCodeField;
            }
            set {
                this.endBillCodeField = value;
            }
        }
        
        /// <remarks/>
        public string hideReverse {
            get {
                return this.hideReverseField;
            }
            set {
                this.hideReverseField = value;
            }
        }
        
        /// <remarks/>
        public string retAddr {
            get {
                return this.retAddrField;
            }
            set {
                this.retAddrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> invFrom {
            get {
                return this.invFromField;
            }
            set {
                this.invFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> invTo {
            get {
                return this.invToField;
            }
            set {
                this.invToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> spid {
            get {
                return this.spidField;
            }
            set {
                this.spidField = value;
            }
        }
        
        /// <remarks/>
        public string emailFlag {
            get {
                return this.emailFlagField;
            }
            set {
                this.emailFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> invFormNo {
            get {
                return this.invFormNoField;
            }
            set {
                this.invFormNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> invoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ctactLinkNo {
            get {
                return this.ctactLinkNoField;
            }
            set {
                this.ctactLinkNoField = value;
            }
        }
        
        /// <remarks/>
        public string processName {
            get {
                return this.processNameField;
            }
            set {
                this.processNameField = value;
            }
        }
        
        /// <remarks/>
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.nmccentral.com/webservices/nmcmapi")]
    public partial class OnTestParms {
        
        private System.Nullable<int> siteNoField;
        
        private System.Nullable<int> systemNoField;
        
        private System.Nullable<int> contactNoField;
        
        private string processFlagField;
        
        private string testCatIDField;
        
        private System.Nullable<int> testSeqNoField;
        
        private string effectiveDateField;
        
        private string expireDateField;
        
        private System.Nullable<int> extendHHField;
        
        private System.Nullable<int> extendMMField;
        
        private string testCommentField;
        
        private string allSystemsFlagField;
        
        private string allZonesFlagField;
        
        private string zonesListField;
        
        private string authPinField;
        
        private string pINField;
        
        private string zoneStateIDField;
        
        private string systemListField;
        
        private string servtype_idField;
        
        private string procNameField;
        
        private string eventIDField;
        
        private decimal alarmIncNoField;
        
        private string serverField;
        
        private string eventDateField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> siteNo {
            get {
                return this.siteNoField;
            }
            set {
                this.siteNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> systemNo {
            get {
                return this.systemNoField;
            }
            set {
                this.systemNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> contactNo {
            get {
                return this.contactNoField;
            }
            set {
                this.contactNoField = value;
            }
        }
        
        /// <remarks/>
        public string processFlag {
            get {
                return this.processFlagField;
            }
            set {
                this.processFlagField = value;
            }
        }
        
        /// <remarks/>
        public string testCatID {
            get {
                return this.testCatIDField;
            }
            set {
                this.testCatIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> testSeqNo {
            get {
                return this.testSeqNoField;
            }
            set {
                this.testSeqNoField = value;
            }
        }
        
        /// <remarks/>
        public string effectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string expireDate {
            get {
                return this.expireDateField;
            }
            set {
                this.expireDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> extendHH {
            get {
                return this.extendHHField;
            }
            set {
                this.extendHHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> extendMM {
            get {
                return this.extendMMField;
            }
            set {
                this.extendMMField = value;
            }
        }
        
        /// <remarks/>
        public string testComment {
            get {
                return this.testCommentField;
            }
            set {
                this.testCommentField = value;
            }
        }
        
        /// <remarks/>
        public string allSystemsFlag {
            get {
                return this.allSystemsFlagField;
            }
            set {
                this.allSystemsFlagField = value;
            }
        }
        
        /// <remarks/>
        public string allZonesFlag {
            get {
                return this.allZonesFlagField;
            }
            set {
                this.allZonesFlagField = value;
            }
        }
        
        /// <remarks/>
        public string zonesList {
            get {
                return this.zonesListField;
            }
            set {
                this.zonesListField = value;
            }
        }
        
        /// <remarks/>
        public string authPin {
            get {
                return this.authPinField;
            }
            set {
                this.authPinField = value;
            }
        }
        
        /// <remarks/>
        public string PIN {
            get {
                return this.pINField;
            }
            set {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        public string zoneStateID {
            get {
                return this.zoneStateIDField;
            }
            set {
                this.zoneStateIDField = value;
            }
        }
        
        /// <remarks/>
        public string systemList {
            get {
                return this.systemListField;
            }
            set {
                this.systemListField = value;
            }
        }
        
        /// <remarks/>
        public string servtype_id {
            get {
                return this.servtype_idField;
            }
            set {
                this.servtype_idField = value;
            }
        }
        
        /// <remarks/>
        public string procName {
            get {
                return this.procNameField;
            }
            set {
                this.procNameField = value;
            }
        }
        
        /// <remarks/>
        public string eventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal alarmIncNo {
            get {
                return this.alarmIncNoField;
            }
            set {
                this.alarmIncNoField = value;
            }
        }
        
        /// <remarks/>
        public string server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
            }
        }
        
        /// <remarks/>
        public string eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ProcessDataCompletedEventHandler(object sender, ProcessDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ProcessDataRequestCompletedEventHandler(object sender, ProcessDataRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessDataRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessDataRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ProcessDataElementRequestCompletedEventHandler(object sender, ProcessDataElementRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessDataElementRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessDataElementRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ProcessDataElementRequest2CompletedEventHandler(object sender, ProcessDataElementRequest2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessDataElementRequest2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessDataElementRequest2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591