//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HS.CommonFunding.CommonFundingApi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonFundingDataResults", Namespace="http://schemas.datacontract.org/2004/07/Service.CommonFunding")]
    [System.SerializableAttribute()]
    public partial class CommonFundingDataResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FailureCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuccessMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailureCode {
            get {
                return this.FailureCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FailureCodeField, value) != true)) {
                    this.FailureCodeField = value;
                    this.RaisePropertyChanged("FailureCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuccessMessage {
            get {
                return this.SuccessMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SuccessMessageField, value) != true)) {
                    this.SuccessMessageField = value;
                    this.RaisePropertyChanged("SuccessMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.nevatech.com/services/", ConfigurationName="CommonFundingApi.IVirtualInterface")]
    public interface IVirtualInterface {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message APIVersionRequest does not match the default value (http://schemas.nevatech.com/services/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonFunding/APIVersion", ReplyAction="http://tempuri.org/ICommonFunding/APIVersionResponse")]
        HS.CommonFunding.CommonFundingApi.APIVersionResponse APIVersion(HS.CommonFunding.CommonFundingApi.APIVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonFunding/APIVersion", ReplyAction="http://tempuri.org/ICommonFunding/APIVersionResponse")]
        System.Threading.Tasks.Task<HS.CommonFunding.CommonFundingApi.APIVersionResponse> APIVersionAsync(HS.CommonFunding.CommonFundingApi.APIVersionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message UpsertCommonFundingDataFromThirdPartyCRMRequest does not match the default value (http://schemas.nevatech.com/services/)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonFunding/UpsertCommonFundingDataFromThirdPartyCRM", ReplyAction="http://tempuri.org/ICommonFunding/UpsertCommonFundingDataFromThirdPartyCRMRespons" +
            "e")]
        HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMResponse UpsertCommonFundingDataFromThirdPartyCRM(HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonFunding/UpsertCommonFundingDataFromThirdPartyCRM", ReplyAction="http://tempuri.org/ICommonFunding/UpsertCommonFundingDataFromThirdPartyCRMRespons" +
            "e")]
        System.Threading.Tasks.Task<HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMResponse> UpsertCommonFundingDataFromThirdPartyCRMAsync(HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="APIVersion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class APIVersionRequest {
        
        public APIVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="APIVersionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class APIVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string APIVersionResult;
        
        public APIVersionResponse() {
        }
        
        public APIVersionResponse(string APIVersionResult) {
            this.APIVersionResult = APIVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpsertCommonFundingDataFromThirdPartyCRM", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpsertCommonFundingDataFromThirdPartyCRMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ApplicationID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string CSNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int ContractID;
        
        public UpsertCommonFundingDataFromThirdPartyCRMRequest() {
        }
        
        public UpsertCommonFundingDataFromThirdPartyCRMRequest(int ApplicationID, string Username, string Password, string CSNumber, int ContractID) {
            this.ApplicationID = ApplicationID;
            this.Username = Username;
            this.Password = Password;
            this.CSNumber = CSNumber;
            this.ContractID = ContractID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpsertCommonFundingDataFromThirdPartyCRMResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpsertCommonFundingDataFromThirdPartyCRMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HS.CommonFunding.CommonFundingApi.CommonFundingDataResults UpsertCommonFundingDataFromThirdPartyCRMResult;
        
        public UpsertCommonFundingDataFromThirdPartyCRMResponse() {
        }
        
        public UpsertCommonFundingDataFromThirdPartyCRMResponse(HS.CommonFunding.CommonFundingApi.CommonFundingDataResults UpsertCommonFundingDataFromThirdPartyCRMResult) {
            this.UpsertCommonFundingDataFromThirdPartyCRMResult = UpsertCommonFundingDataFromThirdPartyCRMResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVirtualInterfaceChannel : HS.CommonFunding.CommonFundingApi.IVirtualInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VirtualInterfaceClient : System.ServiceModel.ClientBase<HS.CommonFunding.CommonFundingApi.IVirtualInterface>, HS.CommonFunding.CommonFundingApi.IVirtualInterface {
        
        public VirtualInterfaceClient() {
        }
        
        public VirtualInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VirtualInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VirtualInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VirtualInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HS.CommonFunding.CommonFundingApi.APIVersionResponse HS.CommonFunding.CommonFundingApi.IVirtualInterface.APIVersion(HS.CommonFunding.CommonFundingApi.APIVersionRequest request) {
            return base.Channel.APIVersion(request);
        }
        
        public string APIVersion() {
            HS.CommonFunding.CommonFundingApi.APIVersionRequest inValue = new HS.CommonFunding.CommonFundingApi.APIVersionRequest();
            HS.CommonFunding.CommonFundingApi.APIVersionResponse retVal = ((HS.CommonFunding.CommonFundingApi.IVirtualInterface)(this)).APIVersion(inValue);
            return retVal.APIVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HS.CommonFunding.CommonFundingApi.APIVersionResponse> HS.CommonFunding.CommonFundingApi.IVirtualInterface.APIVersionAsync(HS.CommonFunding.CommonFundingApi.APIVersionRequest request) {
            return base.Channel.APIVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<HS.CommonFunding.CommonFundingApi.APIVersionResponse> APIVersionAsync() {
            HS.CommonFunding.CommonFundingApi.APIVersionRequest inValue = new HS.CommonFunding.CommonFundingApi.APIVersionRequest();
            return ((HS.CommonFunding.CommonFundingApi.IVirtualInterface)(this)).APIVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMResponse HS.CommonFunding.CommonFundingApi.IVirtualInterface.UpsertCommonFundingDataFromThirdPartyCRM(HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMRequest request) {
            return base.Channel.UpsertCommonFundingDataFromThirdPartyCRM(request);
        }
        
        public HS.CommonFunding.CommonFundingApi.CommonFundingDataResults UpsertCommonFundingDataFromThirdPartyCRM(int ApplicationID, string Username, string Password, string CSNumber, int ContractID) {
            HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMRequest inValue = new HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMRequest();
            inValue.ApplicationID = ApplicationID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.CSNumber = CSNumber;
            inValue.ContractID = ContractID;
            HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMResponse retVal = ((HS.CommonFunding.CommonFundingApi.IVirtualInterface)(this)).UpsertCommonFundingDataFromThirdPartyCRM(inValue);
            return retVal.UpsertCommonFundingDataFromThirdPartyCRMResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMResponse> HS.CommonFunding.CommonFundingApi.IVirtualInterface.UpsertCommonFundingDataFromThirdPartyCRMAsync(HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMRequest request) {
            return base.Channel.UpsertCommonFundingDataFromThirdPartyCRMAsync(request);
        }
        
        public System.Threading.Tasks.Task<HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMResponse> UpsertCommonFundingDataFromThirdPartyCRMAsync(int ApplicationID, string Username, string Password, string CSNumber, int ContractID) {
            HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMRequest inValue = new HS.CommonFunding.CommonFundingApi.UpsertCommonFundingDataFromThirdPartyCRMRequest();
            inValue.ApplicationID = ApplicationID;
            inValue.Username = Username;
            inValue.Password = Password;
            inValue.CSNumber = CSNumber;
            inValue.ContractID = ContractID;
            return ((HS.CommonFunding.CommonFundingApi.IVirtualInterface)(this)).UpsertCommonFundingDataFromThirdPartyCRMAsync(inValue);
        }
    }
}
